### ISSUE TITLE
SMA time now set incorrectly

### ISSUE THREAD

**Issue by tardisx** [nottledim/pvsolar#2]
Thanks for writing the sboy tool - one of the few that just does the fetching of data and doesn't concern itself with storing in SQL databases and the like.

However I've found a problem with respect to time handling. This example probably demonstrates it:

```
pi@raspberrypi:~ $ date ; sboy --address=xx:xx:xx:xx:xx:xx --device=xx:xx:xx:xx:xx:xx -d -b
Fri Dec  4 10:26:41 ACDT 2015
Sboy 2012-11-15 1603
Bluetooth Sig Strength: 69.1%
DC volts: 274.6V  current: 0.000A   power: 0.000W
Current power = 418 Watt
E total today = 15.349 kW.h
Meter total = 7474.94 kW.h
Time of reading: 23:56 GMT  3 Dec 2015

pi@raspberrypi:~ $ date ; sboy --address=xx:xx:xx:xx:xx:xx --device=xx:xx:xx:xx:xx:xx -d -b
Fri Dec  4 10:31:31 ACDT 2015
Sboy 2012-11-15 1603
Bluetooth Sig Strength: 69.5%
DC volts: 278.8V  current: 0.000A   power: 0.000W
Current power = 681 Watt
E total today = 0.015 kW.h
Meter total = 7474.98 kW.h
Time of reading: 00:01 GMT  4 Dec 2015
```

The inverter thinks that GMT is my timezone and doesn't roll over the "E total today" until 10:30am each day.

I've since disabled the part of the code that sets the time, but the damage is done and the inverter now thinks it lives in the UK :-)

Is there any way to fix this?

Cheers.

**Comment by nottledim** [comment]
On 12/04/15 00:15, Justin Hawkins wrote:
> Thanks for writing the sboy tool - one of the few that just does the fetching
> of data and doesn't concern itself with storing in SQL databases and the like.

It's nice to know somebody uses it :-)

......

> The inverter thinks that GMT is my timezone and doesn't roll over the "E total
> today" until 10:30am each day.

Yes,  it's not really GMT it's more UTC or unix-time.  I knew there'd be a
problem with time for those in other parts of the world although I didn't
really anticipate this particular one.

There's a few things you could do:

  1) move all your kit to the UK not forgetting to bring some sunshine with
you. :-)

  2) probably the best thing is to change the calls to gmtime in sboy.c to
localtime.  I don't know enough about the inverter to be sure that's going to
be a final solution but you can try.

  3) set the time manually through inverter configuration menu and don't use
sboy to set the time.

> I've since disabled the part of the code that sets the time, but the damage is
> done and the inverter now thinks it lives in the UK :-)

Yes, my inverter is set to some time in the year 2169 or somesuch as a result
of my mucking about trying to get to talk to it.  I can probably reset it from
the front panel but that'd be an adventure in itself for me.

What I do is set the inverter time as soon as I hear from it in the morning.
It doesn't save the setting overnight unfortunately.  This works fine unless
the inverter goes off during the day (e.g as a result of a very dark storm).

However setting the time isn't really an intended part of the pvsolar design
concept.  So far as the data is concerned the time of reading from the host is
the best way.  The inverter should be configured correctly whereupon it should
change days as expected.

Does that help at all?

Let me know.

Dick

-- 
Dick Middleton
dick@lingbrae.com

**Comment by nottledim** [comment]
On 12/04/15 00:15, Justin Hawkins wrote:

>  2) probably the best thing is to change the calls to gmtime in sboy.c to
> localtime.  I don't know enough about the inverter to be sure that's going >
to be a final solution but you can try.

I don't think this does what I thought it did. It's a while since I looked at
this code. There is a variable called tzOffset in the setTime function.  It it
probably the thing that should be changed.   It will be number of seconds from
GMT.  You should be (guessing) negative -37800 if Google is correct that
you're 10hrs 30mins ahead.

Try it  - if it works I can add a tzOffset option.

Cheers

Dick

-- 
Dick Middleton
dick@lingbrae.com

**Comment by tardisx** [comment]
It looks like that's done it:

Sboy 2012-11-15 1603
Time set to: 23:57 GMT  4 Dec 2015
Bluetooth Sig Strength: 69.5%
DC volts: 271.5V  current: 0.000A   power: 0.000W
Current power = 631 Watt
E total today = 0.626 kW.h
Meter total = 7487.29 kW.h
Time of reading: 23:57 GMT  4 Dec 2015

(that was a few minutes before the midnight rollover @ GMT).

I'll let it run and see if it rolls over properly tomorrow.

(the actual symptom as that I was uploading to pvoutput, and pvoutput would not "roll over" for the day, since it had already seen higher E Today values - even after 10:30am it would not reset - though sboy was producing correct values by then).

**Comment by tardisx** [comment]
Just while I'm dreaming, I guess the "correct-est" solution would be to be able to supply a time zone name (from the TZ database), in my case 'Australia/South' and have it always apply the correct offset (no need to mess with it for daylight savings).

**Comment by tardisx** [comment]
Yep all good today:

```
Sboy 2012-11-15 1603
Bluetooth Sig Strength: 69.5%
DC volts: 267.8V  current: 0.000A   power: 0.000W
Current power = 91 Watt
E total today = 0.222 kW.h
Meter total = 7500.91 kW.h
Time of reading: 21:57 GMT  5 Dec 2015
```

:-) Thanks!

**Comment by nottledim** [comment]
Glad you've got it working. But what did you change? Just the tzone value 
or change the gmtime calls?

Dick

**Comment by tardisx** [comment]
Yep - just changed the 'tzOffset' variable, hardcoding the -37800 seconds as you suggested.

**Comment by nottledim** [comment]
On 12/05/15 22:39, Justin Hawkins wrote:
> Yep - just changed the 'tzOffset' variable, hardcoding the -37800 seconds as
> you suggested.

I pushed a new version of sboy to github with the capability of having a tz
offset on the set-time option:

sboy --set-time=-38700
sboy -t-38700
sboy -t

etc

I've done very limited testing.  If you can give it try and report any issues
that would be good. Many thanks.

Dick

-- 
Dick Middleton
dick@lingbrae.com

**Comment by tardisx** [comment]
I have installed it, I won't be able to make a judgement on it working until tomorrow morning. Will let you know!

Just FYI,

>  1) move all your kit to the UK not forgetting to bring some sunshine with you. :-)

I tried this, didn't work out :-)

**Comment by tardisx** [comment]
Looks good to me, thanks!
